# This file is here for reverse compatibility. Older versions of the firmware
# pointed to `config.yaml` instead of `base.yaml`. That file also included the
# config found in `stock.yaml`, which is why it's being included here.

# Please use `base.yaml` for new configurations and customizations.

packages:
  stock: !include stock.yaml